version: "3.9"

services:
  python-ml:
    build:
      context: ./python-ml
    ports:
      - "8000:8000"
    networks:
      - hallu-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/verify"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - PYTHONUNBUFFERED=1

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=factcheck
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - hallu-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 10s
      timeout: 5s
      retries: 5

  weaviate:
    image: semitechnologies/weaviate:1.26.1
    ports:
      - "8080:8080"
    environment:
      - QUERY_DEFAULTS_LIMIT=20
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=text2vec-transformers
      - ENABLE_MODULES=text2vec-transformers
    volumes:
      - weaviate-data:/var/lib/weaviate
    networks:
      - hallu-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/.well-known/ready"]
      interval: 30s
      timeout: 10s
      retries: 3

  java-backend:
    build:
      context: ./java-backend
    ports:
      - "8081:8080" # Alterado para evitar conflito com Weaviate
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/factcheck
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pass
      - WEAVIATE_URL=http://weaviate:8080
      - PYTHON_SERVICE_URL=http://python-ml:8000/verify
    depends_on:
      python-ml:
        condition: service_healthy
      postgres:
        condition: service_healthy
      weaviate:
        condition: service_healthy
    networks:
      - hallu-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  hallu-net:
    driver: bridge

volumes:
  postgres-data:
  weaviate-data:
